# This file was made by Andrew
# Requires deletion of previous dist folder if it exists before running

name: Build and generate nuxt project on merge or pull request

on:
  push:
    branches:
      - 'master' 
    paths:
      - "augmented-reality/public/v8/**"

jobs:
  build_and_generate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        directory-path: ./augmented-reality/public/v8/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build for production
      working-directory: ${{ matrix.directory-path }}
      run: npm run build
    - name: Generate static project
      working-directory: ${{ matrix.directory-path }}
      run: npm run generate
