# This file was made by Andrew
# Requires deletion of previous dist folder if it exists before running

name: Build and generate nuxt project on merge or pull request

on:
  push:
    branches:
      - 'master' 
    paths:
      - "augmented-reality/public/v8/**"

jobs:
  build_and_generate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        cd augmented-reality/public/v8
        npm ci

    - name: Build for production
      run: |
        cd augmented-reality/public/v8
        npm run build

    - name: Generate static project
      run: |
        cd augmented-reality/public/v8
        npm run generate
